spring:
  application:
    name: adas
  docker:
    compose:
      enabled: false
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:default}
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:adas}?useSSL=false&allowPublicKeyRetrieval=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: ${DB_USER:secret}
    password: ${DB_PASSWORD:verysecret}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
    database-platform: org.hibernate.dialect.MySQLDialect
  sql:
    init:
      mode: never

logging:
  level:
    com.adas.api: INFO

springdoc:
  swagger-ui:
    path: /docs
  api-docs:
    path: /v3/api-docs

media:
  ffprobe-path: ffprobe
  probe-timeout-ms: 5000

external:
  stt:
    base-url: http://localhost:8001/api/v1
    connect-timeout-ms: 5000
    response-timeout-ms: 30000
    read-timeout-ms: 30000
    write-timeout-ms: 30000
  diarization:
    base-url: http://localhost:8002/api/v1
    connect-timeout-ms: 5000
    response-timeout-ms: 60000
    read-timeout-ms: 60000
    write-timeout-ms: 60000

# Google STT 설정 테스트
google:
  stt:
    credentials-path: ${GOOGLE_APPLICATION_CREDENTIALS:C:/google-credentials/adas-stt-key.json}
    project-id: ${GOOGLE_PROJECT_ID:your-project-id}
    language-code: ko-KR
