spring:
  application:
    name: adas

logging:
  level:
    com.adas.api: INFO

springdoc:
  swagger-ui:
    path: /docs
  api-docs:
    path: /v3/api-docs

media:
  ffprobe-path: ffprobe
  probe-timeout-ms: 5000

external:
  stt:
    base-url: http://localhost:8001/api/v1
    connect-timeout-ms: 5000
    response-timeout-ms: 30000
    read-timeout-ms: 30000
    write-timeout-ms: 30000
  diarization:
    base-url: http://localhost:8002/api/v1
    connect-timeout-ms: 5000
    response-timeout-ms: 60000
    read-timeout-ms: 60000
    write-timeout-ms: 60000
