services:
  db:
    image: mysql:latest
    container_name: adas-mysql
    environment:
      MYSQL_DATABASE: adas
      MYSQL_USER: secret
      MYSQL_PASSWORD: verysecret
      MYSQL_ROOT_PASSWORD: verysecret
    ports: ['3306:3306']

  api:
    labels:
      org.springframework.boot.ignore: true
    build:
      context: ./backend/api
      dockerfile: Dockerfile
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_NAME: adas
      DB_PASSWORD: verysecret
      # SPRING_PROFILES_ACTIVE: dev
    depends_on: [db]
    # 외부 8081 -> 컨테이너 8080 (Spring Boot 기본 포트)
    ports: ['8081:8080']

#  diarization:
#    build:
#      context: ./backend/diarization
#      dockerfile: backend/api/api/Dockerfile
#    ports: ['8082:8082']

#  stt:
#    build:
#      context: ./backend/stt
#      dockerfile: backend/api/api/Dockerfile
#    ports: ['8083:8083']
